-- Add new recruitment status values
ALTER TYPE recruitment_status ADD VALUE IF NOT EXISTS 'INVITED_TO_INTERVIEW' AFTER 'ACCEPTED';
ALTER TYPE recruitment_status ADD VALUE IF NOT EXISTS 'AWAITING_DECISION' AFTER 'INVITED_TO_INTERVIEW'; 